### ISSUE TITLE
Devcontainer Setup on MacOS broken

### ISSUE THREAD

**Issue by joneugster** [leanprover-community/NNG4#35]
For me, the vscode devcontainer setup fails with the following error.

MacOS 12.4
Works fine on Linux (Tuxedo OS)

```

[12262 ms] 
[12263 ms] Start: Run in container: /bin/sh -c (cd ~/lean4game && npm install)
[12264 ms] Start: Run in container: /bin/sh -c (cd ~/game && lake update && lake exe cache get && lake build)
[12446 ms] [10:50:57] Installing extension 'leanprover.lean4'...
[12612 ms] [10:50:57] Getting Manifest... leanprover.lean4
[12749 ms] [10:50:57] Installing extension: leanprover.lean4
[13872 ms] [10:50:58] Extracted extension to file:///home/node/.vscode-server/extensions/leanprover.lean4-0.0.117: leanprover.lean4
[13881 ms] [10:50:58] Renamed to /home/node/.vscode-server/extensions/leanprover.lean4-0.0.117
[13888 ms] [10:50:58] Extracting extension completed. leanprover.lean4
[13900 ms] [10:50:58] Extension installed successfully: leanprover.lean4
[13902 ms] [10:50:58] Extension 'leanprover.lean4' v0.0.117 was successfully installed.
[13907 ms] [10:50:58] No uninstalled extensions found.
[43102 ms] onCreateCommand failed with exit code 2. Skipping any further user-provided commands.
[43109 ms] Error: Command failed: /bin/sh -c (cd ~/game && lake update && lake exe cache get && lake build)
[43110 ms]     at OY (/Users/jon/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:235:130)
[43110 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[43110 ms]     at async Nl (/Users/jon/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:227:4393)
[43110 ms]     at async Rl (/Users/jon/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:227:3738)
[43110 ms]     at async Ml (/Users/jon/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:227:2745)
[43111 ms]     at async gtA (/Users/jon/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:611:31559)
[43111 ms]     at async stA (/Users/jon/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:611:28792)
[43128 ms] Exit code 1
[43134 ms] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/jon/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js run-user-commands --user-data-folder /Users/jon/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-2d025710-0709-4b28-a1ae-8efb847311ec1698403843119 --workspace-folder /Users/jon/Documents/Computer/Lean/NNG4 --id-label devcontainer.local_folder=/Users/jon/Documents/Computer/Lean/NNG4 --id-label devcontainer.config_file=/Users/jon/Documents/Computer/Lean/NNG4/.devcontainer/devcontainer.json --container-id cbeddccf211d4470adf4b67618abae44ef3a3f72da59d25301f3644e33fb4d40 --log-level debug --log-format json --config /Users/jon/Documents/Computer/Lean/NNG4/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --skip-non-blocking-commands true --prebuild false --stop-for-personalization true --remote-env REMOTE_CONTAINERS_IPC=/tmp/vscode-remote-containers-ipc-80f8143d-cbac-4bf3-a587-f5c0ffab2265.sock --remote-env SSH_AUTH_SOCK=/tmp/vscode-ssh-auth-80f8143d-cbac-4bf3-a587-f5c0ffab2265.sock --remote-env DISPLAY=:0 --remote-env REMOTE_CONTAINERS_DISPLAY_SOCK=/tmp/.X11-unix/X0 --remote-env REMOTE_CONTAINERS=true --mount-workspace-git-root --dotfiles-target-path ~/dotfiles
[43135 ms] Exit code 1
[51034 ms] Error opening dev container configurations: CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f55736572732f6a6f6e2f446f63756d656e74732f436f6d70757465722f4c65616e2f4e4e4734222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f6a6f6e2f446f63756d656e74732f436f6d70757465722f4c65616e2f4e4e47342f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f6a6f6e2f446f63756d656e74732f436f6d70757465722f4c65616e2f4e4e47342f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f6a6f6e2f446f63756d656e74732f436f6d70757465722f4c65616e2f4e4e47342f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/home/node/game'
    at r.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:645:11397)
    at async r.exists (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:645:13603)
    at async Promise.all (index 0)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1861:2796
```

**Comment by joneugster** [comment]
I believe this has been resolved
